### PR TITLE
Add example using billiard systems

### PR DESCRIPTION
**Pull request by Datseris**
Comments welcome :) 

The notebook was generated from Literate.jl but it was also run a single time because PyPlot doesn't capture figures in Literate, only IJulia.

### CODE REVIEW

**Comment by floswald** [comment]
hey! looks like a very cool example. just a quick thought: I have moved away from PyPlot for several reasons, mainly because GR got so good recently. GR is also the default backend for Plots now. maybe the problem you mention would go away when using Plots (GR) instead?

**Comment by Datseris** [comment]
Yeah, it will. But I am waiting for Makie anyway, I won't be using Plots at all. When makie is at a stable and feature-full state I will move `DynamicalBilliards` there, but for now, PyPlot is vastly superior for my work to anything else, and the only shortcomings of PyPlot are that "it is not Julia".

**Comment by floswald** [comment]
I see - any timeline on that makie release?

**Comment by johnfgibson** [comment]
Can I just say that is totally awesome and exactly what I had in mind? Thank you for getting this collection rolling!

**Pull request merged**
